<?php

namespace Conectala\CacheWrapper\Helpers\Cache;

class Tag extends Parts
{
    public static function build(array $parameters): string
    {
        if (class_exists('\App\Helpers\Cache\Tag')) {
            return ($class = '\App\Helpers\Cache\Tag')::build($parameters);
        }
        if (class_exists('\Conectala\MultiTenant\Helpers\Cache\Tag')) {
            return ($class = '\Conectala\MultiTenant\Helpers\Cache\Tag')::build($parameters);
        }
        return parent::build($parameters); // TODO: Change the autogenerated stub
    }
}
